### ISSUE TITLE
About labeling data?

### ISSUE THREAD

**Issue by K-M-Ibrahim-Khalilullah** [jasonccai/HeadCTSegmentation#2]
Thanks for nice repo
Would you tell me about labeling data (label names)?
That means, what represented the labels 0-16? The name of the corresponding label. 
As for example, the label '1' represents 'Frontal Lobe' (just as example here).

Thanks in advance

**Comment by jasonccai** [comment]
Hi ML-Boss,
Thanks for your interest!
The labels can be found here: https://jasonccai.github.io/HeadCTSegmentation/
